#!/bin/sh

set -eu

MINIMUM_GLIBC_VERSION=2.17

app=jetbrains-toolbox

cd "$APPDIR"

glibcversion="./glibcversion"
if [ -f $glibcversion ]
then
  if [ "$($glibcversion | tr . 0)" -lt "$(echo $MINIMUM_GLIBC_VERSION | tr . 0)" ]
  then
    echo "The minimum supported glibc version is $MINIMUM_GLIBC_VERSION, detected $($glibcversion)"
    echo "Please update your system"
    notify-send "Cannot start JetBrains Toolbox. The minimum supported glibc version is $MINIMUM_GLIBC_VERSION, detected $($glibcversion). Please update your system" -i ./toolbox.svg
    exit 2
  fi
fi

export JETBRAINS_TOOLBOX_LD_LIBRARY_PATH=${LD_LIBRARY_PATH-toolboxvarunset0a732ef1e2b11070e7ee9dfcb89ee6e34}
export LD_LIBRARY_PATH=.:${LD_LIBRARY_PATH:-}

toolboxconfig=${XDG_CONFIG_HOME:-$HOME/.config}/JetBrains/Toolbox/toolboxrc
if [ -f "$toolboxconfig" ]
then
    # shellcheck disable=SC1090
    . "$toolboxconfig"
fi

unset ARGV0

exec ./$app "$@"
